config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('mailinglist/', include('mailinglist.urls', namespace='mailinglist')),
]

mailinglist/urls.py
from django.urls import path
from mailinglist import views

app_name = 'mailinglist'
urlpatterns = [
    path('', views.MailingListListView.as_view(), name='mailinglist_list'),
    path('new', views.CreateMailingListView.as_view(), name='create_mailinglist'),
    path('<uuid:pk>/delete',
        views.DeleteMailingListView.as_view(),
        name='delete_mailinglist'),
    path('<uuid:pk>/manage', 
        views.MailingListDetailView.as_view(),
        name='manage_mailinglist'),
    path('<uuid:mailinglist_id>/subscribe', 
        views.SubscribeToMailingListView.as_view(),
        name='subscribe'),
    path('<uuid:pk>/thankyou', 
        views.ThankYouForSubscribingView.as_view(),
        name='subscriber_thankyou'),
    path('subscribe/confirmation/<uuid:pk>', 
        views.ConfirmSubscriptionView.as_view(),
        name='confirm_subscription'),
    path('unsubscribe/<uuid:pk>', 
        views.UnSubscribeView.as_view(),
        name='unsubscribe'),
    path('unsubscribe/<uuid:mailinglist_pk>/message/new', 
        views.CreateMessageView.as_view(),
        name='create_message'),
    path('message/<uuid:pk>', 
        views.MessageDetailView.as_view(),
        name='view_message'),
    
    # api routes
    path('api/v1/mailing-list', views.MailingListCreateListView.as_view(),
        name='api-mailing-list-list'),
    path('api/v1/mailing-list/<uuid:pk>',
        views.MailingListRetrieveUpdateDestroyView.as_view(),
        name='api-mailing-list-detail'),
    path('api/v1/mailing-list/<uuid:mailing_list_pk>/subscribers',
        views.SubscriberListCreateView.as_view(),
        name='api-subscriber-list'),
    path('api/v1/subscriber/<uuid:pk>',
        views.SubscriberRetrieveUpdateDestroyView.as_view(),
        name='api-subscriber-detail'),
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from user import views

app_name = 'user'
urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', views.RegisterView.as_view(), name='register'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-light bg-light">
            <a href="#" class="navbar-brand">Mail Ape</a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'mailinglist:mailinglist_list' %}" class="nav-link">
                        Your Mailing Lists
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'user:logout' %}" class="nav-link">
                            Logout
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'user:login' %}" class="nav-link">
                            Login
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'user:register' %}" class="nav-link">
                            Register
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>

        {% block body %}
        
        {% endblock body %}
    </div>

    
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>